version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8443:8443"     # TLS port exposed to host
    depends_on:
      - user_management
      - game_service
      - chat_service
    volumes:
      - ./api-gateway:/app
      - /app/node_modules      # use container-installed deps
    env_file:
      - .env
    restart: always
    networks:
      - backend

  user_management:
    build: ./user_management
    expose:
      - "9001"
    networks:
      - backend

  game_service:
    build: ./game_service
    expose:
      - "9002"
    networks:
      - backend

  chat_service:
    build: ./chat_service
    expose:
      - "9003"
    networks:
      - backend

networks:
  backend:
    driver: bridge